# Generated by Django 3.1 on 2020-08-12 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourierAgency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('update_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'courier_agenecy',
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('update_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'destnation',
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_two_kg_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('per_kilo_thereafter', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('update_on', models.DateTimeField(auto_now=True)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LogisticForOrder.courieragency')),
                ('from_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='From', to='LogisticForOrder.destination')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='To', to='LogisticForOrder.destination')),
            ],
            options={
                'db_table': 'rate_card',
                'ordering': ['created_on'],
            },
        ),
    ]
