# Generated by Django 3.1 on 2020-08-12 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LogisticForOrder', '0002_auto_20200812_0844'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courieragency',
            options={'ordering': ['created_on'], 'verbose_name_plural': 'courier Agenecies'},
        ),
    ]
