# Generated by Django 3.1 on 2020-08-12 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogisticForOrder', '0003_auto_20200812_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='courieragency',
            name='min_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
